### ISSUE TITLE
How to set up/install

### ISSUE THREAD

**Issue by MortMort** [BarsikV/CommunicationDeviceSwitcherService#2]
Hello. I guess i'm a noob. don't know how to set this up to run. I ran Install service script.ps1 but the powershell only popped up very shortly and then closed down again. Help pl0x.

**Comment by travisterrell** [comment]
It's been almost a month, but perhaps you're still interested in this issue. I just discovered this awesome-looking service, and typed out all of the following to help you before installing it myself...but then I actually installed it, and ran into an error (which I suspect is what is causing you problems as well.) I'm going to leave the original reply for posterity, and because it contains information on verifying services are running, and running PS scripts in a better way.

The problem I encountered was that the PS script was unable to start the service after install, providing a generic error. After verifying that the service was present in services.msc, I tried starting it from there, but again got a (more verbose) error, "The system cannot find the file specified." I don't have the time to debug this code now (I downloaded this so that I could save time haha), though I suspect it's a probably a pretty simple bug. Unfortunately, it looks like the original poster isn't really providing support, and was just sharing a tool he made for himself. If I ever do actually get around to looking at this and fixing it, I'll be sure to reply to this so that you can use it.


**Original reply:**
If you ran the script, the service should be installed and started. You can verify this by viewing your services--press CTRL+R, then type _services.msc_. From there, look for the service named "Communication Audio Auto Switch Service". It should be present, and say "running." If it's not running, Right-click -> Start. If it doesn't exist at all, try the install again, but as run it as administrator. Also, rather than double-clicking to run it, open up an administrative PowerShell window (or the PowerShell ISE--which is what we'll do here so you can just use a GUI). Running a script this way lets you see the output of it, rather than it disappearing after completion as it does when you double-click it.

To do so: 
Start->search for "powershell," right-click "Windows PowerShell ISE, click "run-as-administrator." Now just File->Open->Select the "Install service script.ps1 script" Now click the green "play button" arrow at the top to run the script. Enjoy, and let me know if you need extra help.

**Comment by MortMort** [comment]
Hello Travis!

Thank you a lot for sending me this. I will definitely look into it later!
I do not know much about services so i am happy about the information about
where to check out services and such ;)

Den tor. 8. apr. 2021 kl. 19.28 skrev Travis J. Terrell <
***@***.***>:

**Comment by BarsikV** [comment]
@travisterrell thank you very much for helping those in need. The info you provided is very helpful!

**Comment by BarsikV** [comment]
All of this shouldn't be a problem anymore in the new release, it should install everything right away in the right places and check for the right .netframework runtime. 
[https://github.com/BarsikV/CommunicationDeviceSwitcherService/releases/tag/1.0.1](Release  #1.0.1)

**Comment by travisterrell** [comment]
No problem! And nice man, thanks so much for the update. I got another job
and never got around to actually fixing it before, so I'm definitely going
to give this a try again.
--
Travis J. Terrell
(937) 589-1994
***@***.***

**Comment by MortMort** [comment]
The update worked flawlessly. Very good job man. I use an application called SoundSwitch in which you can select audio device to switch between with a shortcut. Makes it super fast to switch between speakers and headset and now, thanks to you, it also switches the discord audio between them. LOVELY!
